<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-barcode' => array(
            'pretty_version' => '1.15.0',
            'version' => '1.15.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-barcode',
            'aliases' => array(),
            'reference' => 'a64455fd9b7068d3b7cba31410f9d34de4de78fe',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-color' => array(
            'pretty_version' => '1.14.6',
            'version' => '1.14.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-color',
            'aliases' => array(),
            'reference' => '83cdb57fd900901c6aa2af8cfd67202518fb69b2',
            'dev_requirement' => false,
        ),
    ),
);
